[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino

; load controller using USBasp via avrdude
upload_protocol = usbasp
upload_command = "${PROJECT_DIR}/USBasp/avrdude.exe" -C "${PROJECT_DIR}/USBasp/avrdude.conf" -c usbasp -p m328p -U flash:w:$SOURCE:i


; Serial Monitor Speed
monitor_speed = 115200

; Default upload speed for standard Nano/Clones
upload_speed = 115200

; Required Libraries (automatically downloaded by PlatformIO)
lib_deps = 
    fmalpartida/LiquidCrystal@^1.5.0

; --- TROUBLESHOOTING UPLOAD FOR HW-TINY CLONES ---
; If uploading fails with "programmer is not responding", 
; change "board = nanoatmega328" above to:
; board = nanoatmega328new
; OR uncomment the line below to force the old bootloader baud rate:
; upload_speed = 57600
